# Generated by Django 4.1.3 on 2022-12-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField()),
                ('author', models.CharField(choices=[('Shahzod ', 'Shahzod'), ('Asilbek', 'Asilbek'), ('Abdullo', 'Abdulo'), ('Nurbek', 'Nurbek'), ("Bilolxo'ja", "Bilolxo'ja")], max_length=20)),
            ],
        ),
    ]
